Feature/profile
kimyoungyin/Nomadcoder-study-community pull request #21
Opened 2021-10-03 13:42 UTC by Zih0

2021-11-08 07:21 UTC, kimyoungyin requested changes
전체적으로 각각 하나의 card를 `div`가 아니라 `form`으로 만드는게 의미적으로 좋을 것 같은데 어떻게 생각하세요?
물론 이를 수정하면 `onClick`을 form의 `onSubmit`으로, handler에 `event.preventDefault()`를 추가해야 합니다.

2021-11-08 07:21 UTC, kimyoungyin commented on src/routes/Profile/index.js
> +  flex-direction: column;
확인해보니 너무 넓어져있네요. 실제 노마드 페이지에서는 `max-width:1280px`로 되어 있으니 이걸 추가하고 
`margin: 0 auto` 같이 중앙정렬 요소도 추가해주면 좋을 것 같아요

2021-11-08 07:21 UTC, kimyoungyin commented on src/routes/Profile/index.js
> +  const nickname = useInput('');
기존 유저의 displayName도 받아와서 해당 프로퍼티가 존재하는 경우에는 useEffect에서 한 번 변경해주는 게 좋을 것 같아요. 저는 가입이 되어 있는데 빈 input에서 시작하면 안 될 것 같네요

2021-11-08 07:21 UTC, kimyoungyin commented on src/routes/Profile/index.js
> +  };
trim()을 한 후 기존 user의 displayName과 비교하여 다른지 판단하는 validation도 있어야 할 것 같아요.

2021-11-08 07:21 UTC, kimyoungyin commented on src/routes/Profile/index.js
> +const Container = styled.div`
background-color가 필요할 것 같네요. 제가 확인한 바로는 저희 theme.grey_50인 것 같은데 확인하고 수정 부탁드립니다!

2021-11-08 07:21 UTC, kimyoungyin commented on src/routes/Profile/index.js
> +`;
`margin-top: 0.5rem`

2021-11-08 07:21 UTC, kimyoungyin commented on src/routes/Profile/index.js
> +                <img src={avatar} alt="profile" />
업데이트 버튼을 누르기 전에 바꾼 이미지를 미리 보여줄 수 있을까요?

2021-11-08 07:21 UTC, kimyoungyin commented on src/routes/Profile/index.js
> +  };
1. 업데이트 버튼을 누르기 전에 바꾼 이미지를 미리 보여줄 수 있을까요?
[트위터 클론코딩 url 이미지 미리보기](https://nomadcoders.co/nwitter/lectures/1925) 
2. avatar state를 그냥 현재 보이는 avatarUrl라고 생각하면 selectedFile state를 따로 만들 필요가 없을 것 같은데 어떠신가요? 물론 그대로 하셔도 상관은 없습니다. 
3. 1번을 해주시면 `setAvatar()`를 `uploadHandler`에서 미리 해주고 `avatarSaveHandler`에서는 기존 이미지 url과 같은지 확인하는 validation과 firebase storage에 이미지를 넣는 것만 담당하는 함수로 만들면 어떨까 싶어요.

2021-11-08 07:21 UTC, kimyoungyin commented on src/routes/Profile/index.js
> +              <label for="delete-checkbox">I understand this action is permanent and no one will be able to undo it</label>
`margin-left: 0.5rem;`

2021-11-08 07:21 UTC, kimyoungyin commented on src/routes/Profile/index.js
> +    if (nickname.value.length < 2) {
`event.preventDefault()`는 form onSubmit이 아니라 필요 없을까요?

2021-11-08 07:21 UTC, kimyoungyin commented on src/routes/Profile/index.js
> +`;
1. 768px 이하일 때 버튼과 checkbox+label이 다른 줄로 정렬
2. text가 wrap될 때 오른쪽 정렬

2021-11-08 07:21 UTC, kimyoungyin commented on src/routes/Profile/index.js
> +              <label for="delete-checkbox">I understand this action is permanent and no one will be able to undo it</label>
"permanent" bold 처리

2021-11-08 07:21 UTC, kimyoungyin commented on src/routes/Profile/index.js
> +              <span>Change Nickname</span>
nickname을 소문자로 하는 게 통일성이 좋지 않을까요?

2021-11-28 11:02 UTC, Zih0 commented on src/routes/Profile/index.js
> +  };
selectedFile에는 파일이 저장되도록 했고, avartar에는 url만 담기도록 수정했습니다.

url이 같은지 검증은 파일명만 다르고 이미지가 같은 경우도 있을 것 같아서, 유의미한 검증이라고 생각하지 않아 적용하진 않았습니다.

2021-11-29 07:10 UTC, kimyoungyin requested changes

2021-11-29 07:10 UTC, kimyoungyin commented on src/routes/Profile/index.js
> +  max-width:1280px;
```suggestion
  max-width:1280px;
```
여기에 max를 주면 그 이상 너비일 때 이상하게 잘려 나옵니다
![스크린샷 2021-11-29 오후 3 47 31](https://user-images.githubusercontent.com/78777345/143821110-00c0ae88-419b-40fa-a3cb-aa19ded54b98.png)
이너 div를 하나 작성해서 거기에 주는 게 좋아보입니다.

2021-11-29 07:10 UTC, kimyoungyin commented on src/routes/Profile/index.js
>  const ProfileCard = styled(Card)`
모든 Card에 너비 768px 이하일 때
`margin-top: 1.25rem;`
![스크린샷 2021-11-29 오후 3 58 39](https://user-images.githubusercontent.com/78777345/143822224-4c3cdf43-8afe-4f6c-b368-d6efb506e7cb.png)
![스크린샷 2021-11-29 오후 3 58 47](https://user-images.githubusercontent.com/78777345/143822231-4c1039c4-eb52-4970-99dd-dd88d5769446.png)

2021-11-29 07:10 UTC, kimyoungyin commented on src/routes/Profile/index.js
>    const avatarSaveHandler = async () => {
여기서 아바타가 변경될 때 Header의 아바타도 변경해줘야 할 것 같아요. recoil로 전역적으로 다루는 것도 좋을 것 같아요.

2021-11-29 07:10 UTC, kimyoungyin commented on src/routes/Profile/index.js
> +  max-width:1280px;
마진도 적용되서 배경색이 잘려 나오니 이 점도 반영해주세요

2021-11-29 07:10 UTC, kimyoungyin commented on src/routes/Profile/index.js
>    const avatarSaveHandler = async () => {
avatarSaveHandler에 대한 내용입니다.

2022-01-11 11:38 UTC, merged