refactor: 핀박스 컴포넌트화
kimyoungyin/Nomadcoder-study-community pull request #25
Opened 2021-11-03 00:35 UTC by Zih0

2021-11-04 00:29 UTC, Zih0 commented
```js
<EditorForm formTitle='글쓰기' role='post' hasCategory={true} />
<EditorForm formTitle='수정하기' role='edit'
 hasCategory={false} />
```
이런식으로 에디터를 가져다가 쓰면 될 것 같습니다!
아직 글 수정하는건 파이어베이스 함수를 못찾아서 이따 퇴근하고 넣도록 하겠습니다.

2021-11-05 12:50 UTC, Zih0 commented
`<EditorForm formTitle='수정하기' role='edit' onSubmit={func} />`

2021-11-05 16:20 UTC, kimyoungyin reviewed
수정 감사합니다 useEffect 부분 확인 부탁드려요!

2021-11-05 16:20 UTC, kimyoungyin commented on src/components/Editor/EditorForm/index.js
> +  }, []);
useEffect로 비동기로 받아오는 건 상위에서 처리해줄 것 같은데 안에 코드들은 그냥 그냥 밖으로 빼도 되지 않을까요?
굳이 componentDidMount에서 처리 안해도 괜찮을 것 같은데 어떠세요?

2021-11-08 06:17 UTC, kimyoungyin commented on src/components/Editor/EditorForm/index.js
> +            history.push("/");
아 push는 상위 handler에서 따로 처리해주는 게 좋을 것 같은데 어떠세요? edit인 경우에는 기존 thread로 돌아갈 것 같은데, threadId를 상위에서 관리하는 게 편할 것 같아서요

2021-11-08 06:17 UTC, kimyoungyin commented on src/routes/Post/index.js
> +    await dbService.collection('threads').add(thread);
여기에 route 이동을 작성해주시면 좋을 것 같아요

2021-11-09 00:32 UTC, Zih0 commented on src/routes/Post/index.js
> +    await dbService.collection('threads').add(thread);
수정완료!

2021-11-10 19:18 UTC, kimyoungyin approved these changes

2021-11-10 19:18 UTC, kimyoungyin commented on src/components/Editor/EditorForm/index.js
> +import { useHistory } from "react-router";
useHistory 안쓰임

2021-11-11 04:22 UTC, Zih0 commented on src/components/Editor/EditorForm/index.js
> -import { useHistory } from "react-router";
@kimyoungyin 
여기 커밋에서 제거했습니다

2021-11-18 18:09 UTC, kimyoungyin reviewed
자잘한 건 제가 수정해서 push할게요

2021-11-18 18:09 UTC, kimyoungyin commented on src/routes/Post/index.js
> +import React, { useEffect } from 'react';
사용하지 않는 useEffect라서 지우면 좋을 것 같아요

2021-11-20 18:33 UTC, kimyoungyin requested changes
오랜만이에요 최근에 바빴네요..
로컬에서 머지한 다음 테스트해봤는데, 에러가 발생해서 코멘트 남겼으니 확인 부탁드려요!

나중에 Loader 컴포넌트도 좀 다듬을 필요가 있어 보이네요.

2021-11-20 18:33 UTC, kimyoungyin commented on src/components/Editor/EditorForm/index.js
> +            return;
이 부분이 editor에서 걸리네요. 이 validation을 post쪽 상위 handler로 옮기거나, title처럼 `prevData.category`로 category state를 초기화 시켜주세요.

2022-01-11 11:35 UTC, merged